name: Bug Report
description: File a bug report to help us improve Better GNOME Clocks
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Better GNOME Clocks are you running?
      options:
        - 1.0.0
        - main branch (latest)
        - other (specify in additional context)
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: Which Linux distribution are you using?
      placeholder: e.g., Ubuntu 22.04, Fedora 38, Arch Linux
    validations:
      required: true

  - type: input
    id: gnome-version
    attributes:
      label: GNOME Version
      description: Which GNOME version are you using?
      placeholder: e.g., GNOME 44, GNOME 45
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: Run with G_MESSAGES_DEBUG=all ./build/src/gnome-clocks

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Custom sound files, specific configurations, etc.
