name: Feature Request
description: Suggest an idea for Better GNOME Clocks
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: Any alternative solutions or features you've considered

  - type: dropdown
    id: willing-to-implement
    attributes:
      label: Would you like to implement this feature?
      description: Let us know if you're willing to contribute
      options:
        - "Yes, I'd like to implement it"
        - "Maybe, with guidance"
        - "No, just suggesting"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
